### ISSUE TITLE
Any plans to convert w3x to json?

### ISSUE THREAD

**Issue by yatyricky** [ChiefOfGxBxL/WC3MapTranslator#11]
like
w3u -> json
w3t -> json
w3a -> json
w3b -> json
w3d -> json
w3q -> json
w3h -> json

**Comment by PhoenixZeng** [comment]
need this too

**Comment by ChiefOfGxBxL** [comment]
Glad to see demand for such a feature. I thought about such a feature back when starting this project, but wasn't sure if it would be used.

I will get started on this feature to translate war3map files into json. I may need 1-2 weekends to get it done as my weeks are busy.

**Comment by yatyricky** [comment]
Really look forward to it. If I had the ability to do it, I'll contribute. But the documents were way too hard for me. Thank you very much!

**Comment by ChiefOfGxBxL** [comment]
Hi @yatyricky and @PhoenixZeng,

v1.0.0 is [published on NPM](https://www.npmjs.com/package/wc3maptranslator) which adds the translation capability from war3map files into JSON. Please have a look and open separate issues for any problems you encounter!

Notes
 * the API is slightly different to support the bi-directional translation. [Refer to the examples](https://github.com/ChiefOfGxBxL/WC3MapTranslator/tree/master/examples) if you need any guidance.
 * the *terrain* translator for war3map --> JSON is not implemented yet, since the format I am using may be changed

**Comment by yatyricky** [comment]
Thank you so much @ChiefOfGxBxL 
Now I have to re-organize all my object data which is not something small.  I'll send feedbacks as soon as I have one.

**Comment by yatyricky** [comment]
w3x to json is only useful when one want to refactor a half done map as far as I concern.
So it would not be that useful compare to json->w3x. But anyways, it should be a core function if someone wants to migrate to Ice-Sickle in the half way.
