### ISSUE TITLE
Update translators to work with 1.32 (Reforged beta)

### ISSUE THREAD

**Issue by ttay24** [ChiefOfGxBxL/WC3MapTranslator#38]
Not sure if anyone has looked at this yet, but do we know which files have changed in the 1.32 Reforged beta?

**Comment by ChiefOfGxBxL** [comment]
I'm still on an older version of WarCraft III so I'm not sure yet. But Blizzard has still indicated they're pursuing the 2019 release, so we don't have much longer until the official version is released and is more stable.

I will certainly be upgrading to Reforged, and will try my hand at deciphering any changes to the data formats they may have made. I don't think it will be much, because a large part of the upgrade is with textures and models. I don't think any entities (placing units, doodads, etc. on the map) will have any changes, but maybe the terrain file will.

**Comment by RobinKa** [comment]
Hey just found this project. I'm also working on fixing another similar tool for 1.32. I already found some changes in the w3i (eg. see [here](https://github.com/sumneko/w3x2lni/pull/58) +8 bytes after each player, and +8 bytes after the header).

**Comment by ChiefOfGxBxL** [comment]
Great, thanks for notifying me of these changes. I'll take a look by this
weekend!

**Comment by ChiefOfGxBxL** [comment]
I've looked at a bare-minimum w3x file saved by the new World Editor. The `.w3i` info file has changed as you mentioned, but I'm getting even more bytes in the header section and after the "Water" section. Please see the attached file for how I break down the bytes in the `.w3i` file ([Attached: wc3 info reforged.txt](https://github.com/ChiefOfGxBxL/WC3MapTranslator/files/4178650/wc3.info.reforged.txt)).

 1. There are 16 bytes in the header section after the editor version
 2. There are 12 bytes after the water section and before the number of players section
 3. There are 8 bytes after each player, as you mentioned, so at least these are accounted for.

I'm going to keep this issue open for a while since this upgrade to support Reforged may take more investigation, and I'd like people to be able to discuss the changes here 💭 

I am uncertain what the new 8 bytes on each player would represent. But for the header, there are some new checkboxes in the Map Options dialog:
![image](https://user-images.githubusercontent.com/4079034/74116398-62e10580-4b81-11ea-9e46-a18faa1f9c47.png)
Maybe the first few checkboxes are some of the unknown w3i flags?

**Comment by RobinKa** [comment]
> ..❔...There are 12 bytes after the water section and before the number of players section

https://github.com/sumneko/w3x2lni/blob/4d31cee553b0be2c8b7d730e92ced496e25d70c5/script/core/slk/frontend_w3i.lua#L147-L156

The first 4 byte were introduced in file version 28 is 0 for Jass and 1 for Lua. Don't know yet what the next 8 are that were introduced in file version 31.

**Comment by ChiefOfGxBxL** [comment]
This issue is being closed with the Release 4.0!

There are two updated translators in Release 4.0 which resolve Reforged changes:
 1. Info
 2. Sounds
